name: Update cvar docs

# Controls when the workflow will run
on:
  pull_request:
    branches: [ main, master ]
    paths:
      - '.github/workflows/docs.yml'
      - '**.sp'
      - '**.inc'
      - '**.md'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-docs:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update docs
        uses: Rainyan/action-sp-cvar-docs@v3
